#!/bin/sh

CWD=/usr/etc/config


# Make sure our script is only being run with root privileges
if [ "$(id -u)" != "0" ];
then
   echo "Error: This script must be run with root privileges." 1>&2
   exit 1
fi

TL_NAME=VimbaUSBTL
#PROFILE_FOLDER=/etc/profile.d
UDEV_FOLDER=/etc/udev/rules.d

if [ -d "$CWD" ]; then
#	TL_SCRIPT_32BIT=${PROFILE_FOLDER}/${TL_NAME}_32bit.sh
    export GENICAM_GENTL32_PATH=$GENICAM_GENTL32_PATH:"$CWD"
	echo "Registering GENICAM_GENTL32_PATH"
#	printf "#!/bin/sh\n\n#Do not edit this file manually because it may be overwritten automatically.\nexport GENICAM_GENTL32_PATH=\$GENICAM_GENTL32_PATH:\"%s\"" $CWD > $TL_SCRIPT_32BIT
#	chmod +x $TL_SCRIPT_32BIT
fi


UDEV_SCRIPT=${UDEV_FOLDER}/99-${TL_NAME}.rules
echo "Registering $TL_NAME device types"
printf "SUBSYSTEM==\"usb\", ACTION==\"add\", ATTRS{idVendor}==\"1ab2\", ATTRS{idProduct}==\"0001\", MODE=\"0666\"\nSUBSYSTEM==\"usb\", ACTION==\"add\", ATTRS{idVendor}==\"1ab2\", ATTRS{idProduct}==\"ff01\", MODE=\"0666\"\n" > $UDEV_SCRIPT

echo "Done"
echo "Please reboot before using the USB transport layer"

